### ISSUE TITLE
Multiple user keys per slice on VM boot.

### ISSUE THREAD

**Issue by llpeterson** [open-cloud/xos#3]
A current limitation is that only one user key is injected into the slice. That user can login and manually add the keys of other users, but an OpenCloud admin also needs to add the keys to the account used to support proxy login to the slice.

**Comment by andybavier** [comment]
It looks like the Nova compute API exposes a key_data field, the contents of which are written to authorized_keys inside the VM.   AFAIK that field could contain multiple SSH keys. However the Nova client doesn't allow setting this field, only key_name.  When key_data is not present, it is generated by looking up key_name.

I think the cleanest option is to extend the Nova client and Ansible nova_compute module to allow key_data to be set directly.  Another advantage is that it will "just work" with the [libvirt hook](https://github.com/andybavier/opencloud-install/blob/juju-ansible/ansible/roles/compute/files/root/etc/libvirt/hooks/qemu) that sets up the proxy forwarding account on the node.

**Comment by andybavier** [comment]
Tony suggested that we use the "--file" argument to the "nova boot" command for this, if that is working in our current infrastructure.  It worked with Essex but gave us problems on Folsom.

**Comment by andybavier** [comment]
We could break this into two problems:

(1) Getting multiple SSH keys into the VM
(2) Copying the SSH keys from inside the VM to set up the proxy login account

For (1) there are a number of ways we could proceed, but probably the cleanest is to use cloud-init.  To add multiple keys we would supply a user-data script:

    #cloud-config
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1...
      - ssh-rsa AAAAB3NzaC1...
... etc.

For (2) we could use guestfish.  Here is a command that copies out all of the SSH authorized keys in all of the user accounts in the VM 'instance-00000034':

`$ guestfish --ro -d instance-00000034 -i glob cat /home/*/.ssh/authorized_keys`

Since we don't know when keys inside the VM have been added or changed, we'd probably want to run this command in a cron job every few minutes for every VM.  It appears to take about 5 seconds per VM to complete.

Some advantages to doing it this way:
* Requires very little code/setup - just a cron job on the nodes, and a script to generate the user-data
* Lets us get rid of a hack to nova-compute where we intercept the key so that we can set up the proxy login account

**Comment by sbconsulting** [comment]
The user-data you're creating for cloud-init is in YAML format? If so, then
it should be straightforward to add this to sync_slivers.py:get_userdata().

My only concern is copying out all of the keys in all of the user accounts
inside the VM. I would be worried about VMs creating account names that
conflict, either unintentionally or intentionally (as some sort of spoofing
or DOS attempt).

I would also anticipate some leakage of nuisance accounts that weren't
intended to be reachable via the NAT interface. For example, the log
aggregation server had an account that was used by HPC nodes to deposit
their logs via rsync over SSH. In an XOS world, that could have been
implemented via a private network between HPC and the log server. (we're
not setting up the log server on XOS, so it's a moot point, just an example
of potential configuration)

Scott

**Comment by andybavier** [comment]
We could stick with copying out keys in the default user accounts (e.g., ubuntu).  This is easy right now since the only images we support are Ubuntu images.

**Comment by sbconsulting** [comment]
That sounds like a plan. Even in the Centos-5.5 image, I named the default
user 'ubuntu'.

Scott
